# Generated by Django 5.2 on 2025-04-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_singer_alter_category_options_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
